# Generated by Django 5.2.7 on 2025-10-07 08:33

import simulation.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_h', models.CharField(blank=True, max_length=64)),
                ('merkle_h', models.CharField(blank=True, max_length=64)),
                ('h', models.CharField(blank=True, max_length=64)),
                ('nonce', models.IntegerField(null=True)),
                ('timestamp', models.FloatField(default=simulation.models.get_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=simulation.models.get_vote)),
                ('timestamp', models.FloatField(default=simulation.models.get_timestamp)),
                ('block_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=simulation.models.get_vote)),
                ('timestamp', models.FloatField(default=simulation.models.get_timestamp)),
                ('block_id', models.IntegerField(null=True)),
            ],
        ),
    ]
